### ISSUE TITLE
Current games issue

### ISSUE THREAD

**Issue by viktordimov** [cnguy/kayn#71]
```js
const nombre = args.slice([1]).join(' ');
const nombreUrl = nombre.replace(/\s/g, "%20").toLowerCase(); 
const summoner = await kayn.Summoner.by.name(nombre)
let game = await kayn.CurrentGame.by.summonerID(summoner.id) // awaiting doesn't solve it
console.log(typeof(game));
```

When trying to see the type of variable `game` if there is no current games for the Summoner, instead of the 404 object, the console returns an "Unhandled promise rejection" and I can't reassign it nor see it's type. Is this an issue or am I doing it wrong?

**Comment by cnguy** [comment]
You forgot to await

```javascript
kayn.CurrentGame.by.summonerID(summoner.id)
```

as well. All of `kayn`'s requests return promises that must be awaited.

**Comment by viktordimov** [comment]
Same result. 
```js
(node:8832) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'then' of undefined
    at Request.catch.callback [as catch] (C:\Users\viks\Desktop\basil\node_modules\kayn\dist\lib\RequestClient\Request.js:67:49)
    at Object.execute (C:\Users\viks\Desktop\basil\comandos\riotAPI.js:46:71)
    at Client.client.on (C:\Users\viks\Desktop\basil\basil.js:55:11)
    at Client.emit (events.js:203:15)
    at MessageCreateHandler.handle (C:\Users\viks\Desktop\basil\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\viks\Desktop\basil\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (C:\Users\viks\Desktop\basil\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\viks\Desktop\basil\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\viks\Desktop\basil\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (C:\Users\viks\Desktop\basil\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (C:\Users\viks\Desktop\basil\node_modules\ws\lib\receiver.js:422:14)
    at Receiver.getData (C:\Users\viks\Desktop\basil\node_modules\ws\lib\receiver.js:352:17)
    at Receiver.startLoop (C:\Users\viks\Desktop\basil\node_modules\ws\lib\receiver.js:138:22)
    at Receiver._write (C:\Users\viks\Desktop\basil\node_modules\ws\lib\receiver.js:74:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Receiver.Writable.write (_stream_writable.js:299:11)
    at TLSSocket.socketOnData (C:\Users\viks\Desktop\basil\node_modules\ws\lib\websocket.js:864:35)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
```

**Comment by cnguy** [comment]
Hmm, I have a feeling that

```javascript
const summoner = await kayn.Summoner.by.name(nombre) // this line
let game = await kayn.CurrentGame.by.summonerID(summoner.id)
```

The commented line may be returning an error.

You can try this:

```javascript
try {
  const summoner = await kayn.Summoner.by.name(nombre)
  let game = await kayn.CurrentGame.by.summonerID(summoner.id) // awaiting doesn't solve it
  console.log(typeof(game));
} catch (error) {
  console.log(error)
}
```

to see what the error is.

**Comment by viktordimov** [comment]
```js
{ statusCode: 404,
  url:
   'https://euw1.api.riotgames.com/lol/spectator/v4/active-games/by-summoner/omitted-the-ID-on-github-comment',
  error:
   { name: 'StatusCodeError',
```
<del>Alright! This worked just fine, now I can reasign with `!game.statusCode === 200`. Must I place `kayn.CurrentGame` inside the Try block, or any call that may return a 404? does it scope it?
Thanks for your help, this saved my day!</del>

**Comment by cnguy** [comment]
If you place it inside the `try` block, the whole try statement will run from start-to-finish unless an error occurs. So you'll be able to catch 404's, 500's, etc of both `Summoner` and `CurrentGame`. Not sure about the scoping part, but IMO if the logic is "combined", then put it all in one `try` block.

I would put it in there personally, unless you want specific error-handling on a case-by-case basis.

**Comment by viktordimov** [comment]
Looks like there's no way to redefine the variable if there is no current game for the summoner, or at least that I'm capable of. Thanks for your help anyway! :)

**Comment by cnguy** [comment]
Ohhh, I haven't been reading carefully. you can try this:

```javascript
const nombre = args.slice([1]).join(' ');
const nombreUrl = nombre.replace(/\s/g, "%20").toLowerCase();
let summoner = null;
try {
  summoner = await kayn.Summoner.by.name(nombre);
} catch (ex) {
  if (ex.statusCode == 404) game = null;
  else throw new Error("completely broken");
}
let game = null;
try {
  game = await kayn.CurrentGame.by.summonerID(summoner.id) // awaiting doesn't solve it
} catch (ex) {
  if (ex.statusCode == 404) game = null;
  else throw new Error("completely broken");
}
console.log(summoner, game)
```

Basically, if there's a 404, just reassign `null`, otherwise if it's some other error that mean something really bad happened (assuming retries are on), so just throw.

**Comment by viktordimov** [comment]
# O M G
So I can actually reasign if the variable is declared outside the  `try{} catch {}` block in the first place?! 
<del>Yes!</del> This returns the current game object if there is one and allows me to reasign game to `"No current games"` if it's value is null due to `ex.statusCode == 404`. No bugs here, just an ES6 noob. 
![Thank you](https://media.giphy.com/media/3oz8xIsloV7zOmt81G/200.gif)

**Comment by cnguy** [comment]
it's okay haha, good luck! I didn't read the question properly so my first answer or 2 were not actually answering the question properly
